Add example wasmer host
carlsverre/wasi-witx-sandbox pull request #7
Opened 2021-10-01 16:41 UTC by Amanieu

This PR adds an example host based on wasmer, using an experimental fork of witx-bindgen that adds support for wasmer (https://github.com/wasmerio/witx-bindgen/tree/wasmer-preview-20211001).

Note that the bindings generator is still a work-in-progress and there may be API changes in the future.

2021-10-01 17:15 UTC, ricochet requested changes
Update the `README ` with:

```md
### wasmtime

```bash
cargo run
# also runnable with:
# cargo run -p example-wasmtime-host
got: [SimpleValue { i: 100 }]
got: [SplitOutput { c: "hello" }, SplitOutput { c: "how" }, SplitOutput { c: "are" }, SplitOutput { c: "you" }]
got: [UserResult { id: 2, username: "lucy", email: "lucy@singlestore.com", phone: "555-123-4567" }, UserResult { id: 4, username: "bob", email: "bob@gmail.com", phone: "555-123-4567" }]
got: [HilbertOutput { idx: "1151918473443465846098964" }]
```

### wasmer

```bash
cargo run -p example-wasmer-host
got: [SimpleValue { i: 100 }]
got: [SplitOutput { c: "hello" }, SplitOutput { c: "how" }, SplitOutput { c: "are" }, SplitOutput { c: "you" }]
got: [UserResult { id: 2, username: "lucy", email: "lucy@singlestore.com", phone: "555-123-4567" }, UserResult { id: 4, username: "bob", email: "bob@gmail.com", phone: "555-123-4567" }]
got: [HilbertOutput { idx: "1151918473443465846098964" }]
```

Also set a default run in `Cargo.toml`:
```toml
default-members = ["crates/example-wasmtime-host"]
```

2021-10-01 17:18 UTC, ricochet requested changes

2021-10-01 17:18 UTC, ricochet commented on .github/workflows/main.yaml
> +          command: run --bin example-wasmer-host
```yaml
command: run
args: -p example-wasmer-host
```

2021-10-01 22:02 UTC, Amanieu commented
Updated.

2021-10-02 20:32 UTC, ricochet approved these changes

2021-10-02 20:42 UTC, merged